version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
   

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - '8000:8000'
    depends_on:
      - backend
    environment:
      - BACKENDPORT=http://backend:3000
    
   